# Generated by Django 3.0.5 on 2020-04-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zanry',
            new_name='Zanr',
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200, verbose_name='Nazev')),
                ('reziser', models.CharField(max_length=100, verbose_name='Reziser')),
                ('popis', models.TextField(blank=True, null=True, verbose_name='Popis filmu')),
                ('delka', models.IntegerField(blank=True, help_text='Zadejte celočíselnou hodnotu', null=True, verbose_name='Delka filmu')),
                ('pristupnost', models.CharField(max_length=20, verbose_name='Pristupnost')),
                ('zanry', models.ManyToManyField(help_text='Vyber zanr pro tento film', to='rezervace.Zanr')),
            ],
            options={
                'ordering': ['nazev'],
            },
        ),
    ]
