# Generated by Django 3.0.5 on 2020-04-27 14:29

from django.db import migrations, models
import rezervace.models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0002_auto_20200426_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='plakat',
            field=models.ImageField(blank=True, null=True, upload_to=rezervace.models.plakat_path, verbose_name='Plakat'),
        ),
    ]
