# Generated by Django 3.0.5 on 2020-06-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0003_film_plakat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projekce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zacatek', models.DateField(blank=True, help_text='Format: <em>YYYY-MM-DD</em>', null=True, verbose_name='Zacatek projekce')),
                ('typ', models.CharField(choices=[('3D', 'Trid'), ('2D', 'Dved')], max_length=10)),
                ('dabing', models.CharField(choices=[('titulky', 'Titulky'), ('cesky', 'Cesky')], max_length=10)),
            ],
            options={
                'ordering': ['zacatek', 'typ'],
            },
        ),
        migrations.CreateModel(
            name='Sal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocet_sedadel', models.IntegerField(blank=True, help_text='Zadejte celočíselnou hodnotu', null=True, verbose_name='Pocet mist')),
            ],
            options={
                'ordering': ['pocet_sedadel'],
            },
        ),
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=20, verbose_name='Jmeno')),
                ('prijmeni', models.CharField(max_length=20, verbose_name='Prijmeni')),
                ('pohlavi', models.CharField(choices=[('zena', 'Zena'), ('muz', 'Muz'), ('jine', 'Jine')], max_length=10)),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
            ],
            options={
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
        migrations.AlterField(
            model_name='film',
            name='pristupnost',
            field=models.CharField(choices=[('Bez omezeni', 'Bez Omezeni'), ('P', 'P'), ('12', 'Dvanact'), ('15', 'Patnact')], max_length=15),
        ),
        migrations.CreateModel(
            name='Rezervace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocet_mist', models.IntegerField(blank=True, help_text='Zadejte celočíselnou hodnotu', null=True, verbose_name='Pocet mist')),
                ('projekce', models.ManyToManyField(help_text='Projekce', to='rezervace.Projekce')),
                ('uzivatel', models.ManyToManyField(help_text='Uzivatel', to='rezervace.Uzivatel')),
            ],
            options={
                'ordering': ['pocet_mist'],
            },
        ),
        migrations.AddField(
            model_name='projekce',
            name='filmy',
            field=models.ManyToManyField(help_text='Vyber film', to='rezervace.Film'),
        ),
        migrations.AddField(
            model_name='projekce',
            name='saly',
            field=models.ManyToManyField(help_text='Vyber pocet sedadel', to='rezervace.Sal'),
        ),
    ]
